prgrms-web-devcourse-final-project/WEB4_5_AnjolinaJelly_BE

- settings.gradle
- src/main/java/com/jelly/zzirit/ZziritApplication.java
- src/test/java/com/jelly/zzirit/ZziritApplicationTests.java
> Closes #5 
- 기존 도메인명(jjirit) 변경에 따라 프로젝트 폴더명을 zzirit로 수정
- Java 패키지명 및 파일명 내부의 도메인명 수정
- 관련 테스트 파일명 수정 (ex: JjiritApplicationTests → ZziritApplicationTests)
- 문서 및 설정 파일 경로에 변경된 폴더명 반영 여부 확인
프로젝트 폴더 및 패키지명 변경이므로 배포 전에 빌드 및 경로 정상 여부 재확인 필요합니다.
폴더명 및 패키지명 변경이 전체 프로젝트 빌드에 문제를 일으키지 않는지 확인 부탁드립니다.
> Chore: 프로젝트 이름, 폴더명 수정 (#5)

- .github/CODEOWNERS
> Closes #9 
- CODEOWNERS 설정
- 프로젝트 내에서 변경 사항이 있으면 전부 다 리뷰어로 등록합니다.
- 아이디 한 번씩 확인 부탁드립니다.
> Chore : 자동 리뷰어 등록 (#9)

- src/main/resources/application.yml
> Closes #15 
- 메일 발송 계정을 기존 메일(Naver) → 팀 계정(Gmail)로 변경
- Gmail SMTP 사용을 위해 앱 비밀번호가 설정되어 있어야 합니다
- ``application-secret.yml` 내 이메일 계정 정보가 반영되어야 정상 동작합니다
> Chore: 인증 메일 발송 계정 변경 (#15)

- src/main/java/com/jelly/zzirit/domain/member/controller/AuthController.java
- src/main/java/com/jelly/zzirit/domain/member/controller/InfoController.java
- src/main/java/com/jelly/zzirit/global/converter/BaseHttpsMessageConverter.java
- src/main/java/com/jelly/zzirit/global/converter/exception/NotSupportedException.java
- src/main/java/com/jelly/zzirit/global/dto/BaseResponse.java
- src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
- src/main/java/com/jelly/zzirit/global/exception/GlobalExceptionHandler.java
- src/main/java/com/jelly/zzirit/global/security/filter/LoginFilter.java
- src/main/java/com/jelly/zzirit/global/security/oauth2/handler/CustomOAuth2FailureHandler.java
- src/main/java/com/jelly/zzirit/global/wrapper/ResponseWrapper.java
> Feat: 공통 응답 처리 개선 (#23)

- src/main/java/com/jelly/zzirit/global/config/AppConfig.java
- src/main/java/com/jelly/zzirit/global/config/securityconfig/CorsConfig.java
- src/main/resources/application.yml
> Closes #27
- 강사님, ft님 주소 cors 허용
> Chore: CORS에 도메인 등록 (#27)

- build.gradle
- src/main/java/com/jelly/zzirit/global/config/SwaggerConfig.java
> Chore: Swagger 설정 추가 (#34)

- src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
- src/main/java/com/jelly/zzirit/domain/order/dto/request/OrderCreateRequest.java
- src/main/java/com/jelly/zzirit/domain/order/dto/response/OrderFetchResponse.java
- src/main/java/com/jelly/zzirit/domain/orderitem/dto/request/OrderItemCreateRequest.java
- src/main/java/com/jelly/zzirit/domain/orderitem/dto/response/OrderItemFetchResponse.java
> Closes #32 
- 주문 생성 API 문서화
- 주문 전체 조회 API 문서화
- 주문 취소 API 문서화
> Docs: 주문 도메인 API 문서화 작업 (#32)

- src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
- src/main/java/com/jelly/zzirit/domain/adminItem/dto/request/ItemCreateRequest.java
- src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
- src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/ImageUploadResponse.java
- src/main/java/com/jelly/zzirit/global/config/securityconfig/SecurityConfig.java
- src/test/java/com/jelly/zzirit/domain/adminItem/Controller/AdminItemControllerTest.java
> Closes #19
- 더미 컨트롤러 작성
- 스웨거 태그 작성
- 컨트롤러 테스트코드 작성 -> 통과했다 안했다 해서 주석 처리해둠
> Docs: 관리자 상품 api 문서화 (#19)

- src/main/java/com/jelly/zzirit/domain/item/controller/BrandController.java
- src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
- src/main/java/com/jelly/zzirit/domain/item/controller/TypeController.java
- src/main/java/com/jelly/zzirit/domain/item/dto/ItemResponse.java
- src/main/java/com/jelly/zzirit/domain/item/dto/SimpleItemResponse.java
- src/main/java/com/jelly/zzirit/domain/item/entity/TimeDealStatus.java
> Closes #37 
- 상품 조회 Swagger 추가
> Docs : 상품 조회 Swagger 작업 (#37)

- src/main/java/com/jelly/zzirit/domain/cart/controller/CartController.java
- src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
- src/main/java/com/jelly/zzirit/domain/cart/dto/request/CartItemAddRequest.java
- src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
> Refactor: 장바구니 도메인 swagger 문서화 (하드코딩) (#33)

- src/main/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealController.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/TimeDealCreateResponse.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/TimeDealModalItem.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/TimeDealResponseDTO.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/entity/TimeDealCreateItem.java
> Closes #이슈번호
- 타임딜 생성 모달
- 타임딜 등록
- 타임딜 목록
- 현재 진행중인 타임딜
> Docs: 타임딜 API 문서화

- src/main/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealController.java
> Docs: 타임딜 API 태그 추가

- src/main/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealController.java
> Docs: 타임딜 API 태그 어노테이션 방식으로 수정

- src/main/java/com/jelly/zzirit/domain/cart/controller/CartController.java
- src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
> Refactor: 장바구니 API 태그 내용 변경 (#43)

- src/main/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealController.java
> Docs: 타임딜 API 태그 수정

- src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
- src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
- src/main/java/com/jelly/zzirit/domain/adminItem/service/QueryAdminItemService.java
- src/main/java/com/jelly/zzirit/domain/item/repository/ItemRepository.java
- src/main/java/com/jelly/zzirit/domain/order/repository/ItemStockRepository.java
- src/main/java/com/jelly/zzirit/global/config/AdminAccountInitializer.java
- src/main/java/com/jelly/zzirit/global/config/securityconfig/SecurityConfig.java
- src/main/java/com/jelly/zzirit/global/dataInit/AdminAccountInitializer.java
> Closes #56
- 관리자 상품 목록 조회 api 구현
- ItemRepository에 메서드 한 개 추가 @Woongbin06 
- ItemStockRepository에 메서드 한 개 추가 @Jinyoung0718 
- 목록 조회 시 N+1문제인지 뭔지 쿼리가 많이 나가는 것 같아요! 일단 이거는 기능 구현 완료 후 이슈 파서 해결하겠습니다!!!
> Feat: 관리자 상품 목록 조회 api 구현 (#56)

- src/main/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealController.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/TimeDealCreateItem.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/TimeDealModalItem.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/TimeDealCreateResponse.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/TimeDealResponseDTO.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/service/TimeDealService.java
- src/test/java/com/jelly/zzirit/domain/timeDeal/controller/TimeDealControllerTest.java
> Closes #59
- 관리자 페이지에서 상품 선택 후 타임딜 생성 버튼 클릭시 요청되는 api 구현
- 타임딜 관련 파일들 위치가 여기저기 들어가 있어서 타임딜 1차 구현 완료 후 위치 재조정 예정입니다
> Feat: 타임딜 등록 페이지 기능 구현 (#59)

- src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
- src/main/java/com/jelly/zzirit/domain/cart/dto/request/CartItemAddRequest.java
- src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartItemResponse.java
- src/main/java/com/jelly/zzirit/domain/cart/entity/CartItem.java
- src/main/java/com/jelly/zzirit/domain/cart/repository/CartItemRepository.java
- src/main/java/com/jelly/zzirit/domain/cart/repository/CartRepository.java
- src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
- src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
- src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
> Closes #82
장바구니 상품 추가, 삭제 기능 구현
(장바구니 조회 시 할인율 계산 제거)
장바구니 조회시에도 페이징이 필요할까요??
> Feat: 장바구니 상품 추가, 삭제 기능 구현 (#82)

- src/main/java/com/jelly/zzirit/domain/item/controller/TimeDealController.java
- src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
- src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDeal.java
- src/main/java/com/jelly/zzirit/domain/item/service/TimeDealService.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/CurruntTimeDeal.java
- src/main/java/com/jelly/zzirit/domain/timeDeal/dto/response/CurruntTimeDealItem.java
- src/test/java/com/jelly/zzirit/domain/item/TimeDealControllerTest.java
> Closes #95
- 진행중인 타임딜 조회 기능 구현
- 테스트용 진행중 타임딜 저장 메서드 작성
- 진행중인 타임딜 조회 테스트(성공) 작성
- Item 엔티티의 status 필드를 EnumType.ORDINAL로 변경
- CHECK 제약조건(item_chk_1)이 숫자 기반으로 설정되어 있어, Enum 저장 방식도 ORDINAL로 통일
> Feat: 진행중인 타임딜 조회 기능 구현 (#95)

- build.gradle
- src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
- src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartItemResponse.java
- src/main/java/com/jelly/zzirit/domain/cart/dto/response/CartResponse.java
- src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
- src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
- src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
- src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
> Closes #97
- 장바구니 도메인 테스트 코드
- 장바구니 response 값 변경
장바구니 response 값이 변경되었습니다 확인 부탁드려요
> Test: 장바구니 도메인 테스트 (#97)

- .github/workflows/deploy.yml
- src/test/java/com/jelly/zzirit/domain/adminItem/Controller/AdminItemControllerTest.java
- src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
- src/test/java/com/jelly/zzirit/domain/item/BrandControllerTest.java
- src/test/java/com/jelly/zzirit/domain/item/TimeDealControllerTest.java
- src/test/java/com/jelly/zzirit/domain/item/TypeControllerTest.java
> Closes #101
- 백엔드 CD 완료
- CI는 웅빈님께 토스..
> Feat: 백엔드 CD (#101)

- .gitignore
- src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
- src/test/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemControllerTest.java
- src/test/java/com/jelly/zzirit/domain/adminItem/service/S3ServiceTest.java
> Closes #115
상품 이미지 업로드 단위 테스트 진행 
itemStatus enum 매핑 방식을 STRING으로 변경
- 테스트 진행 시 이미지가 계속 S3에 업로드 될 수 있을 것 같아 코드는 주석 처리해서 올립니다.
- itemStatus enum 매핑 방식을 STRING으로 변경해서 올렸는데 해당 부분 확인이 필요합니다.
> Test: 상품 이미지 업로드 테스트 (#115)

- src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
- src/main/java/com/jelly/zzirit/domain/order/dto/request/OrderCreateRequest.java
- src/main/java/com/jelly/zzirit/domain/order/dto/request/OrderItemCreateRequest.java
> Closes #111 
- 주문 생성 API 삭제 -> 결제 도메인으로 기능 통합
- 주문 생성 요청 DTO 삭제
> Chore: 사용하지 않는 주문 생성 API 삭제 (#111)

- src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
> Closes #117 
- 늦게 올라간 pr이 먼저 병합되는 과정에서 잘못된 enum타입(ORDINAL)이 반영 된것을 수정
> Fix: ItemStatus enum 타입을 STRING으로 재변경 (#117)

- src/main/java/com/jelly/zzirit/domain/adminItem/controller/AdminItemController.java
- src/main/java/com/jelly/zzirit/domain/adminItem/dto/request/ItemCreateRequest.java
- src/main/java/com/jelly/zzirit/domain/adminItem/dto/response/AdminItemResponse.java
- src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
> Closes #110
가격 int -> bigdecimal로 변경(조회, 등록, 수정)
조회 시 재고 수량 둘 다 주게 변경(수량, 판매된 수량)
상품 등록 시 이미지 url 필수
> Feat: 코드에 API 변경 사항 반영 (#110)

- src/main/java/com/jelly/zzirit/domain/item/dto/request/TimeDealSearchCondition.java
- src/main/java/com/jelly/zzirit/domain/item/service/QueryTimeDealService.java
- src/main/java/com/jelly/zzirit/domain/item/service/TimeDealService.java
> Closes #121
- 타임딜 관리자 검색 API에서 아무런 조건도 넣지 않으면 전체 타임딜이 반환되는 기능 구현
> Feat: 타임딜 검색 API에서 조건 없이 전체 조회하는 기능 구현 (#121)

- src/main/java/com/jelly/zzirit/domain/cart/controller/CartItemController.java
- src/main/java/com/jelly/zzirit/domain/cart/service/CartItemService.java
- src/main/java/com/jelly/zzirit/domain/cart/service/CartService.java
- src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
- src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
- src/test/java/com/jelly/zzirit/domain/cart/service/CartItemServiceTest.java
- src/test/java/com/jelly/zzirit/domain/cart/service/CartServiceTest.java
> Closes #136
- 장바구니 상품 전체 수량 및 금액 집계 로직 개선
- 수량 증감 API 단일 상품 응답으로 변경
- 장바구니 도메인 단위 테스트 코드 작성
> Test: 장바구니 도메인 단위 테스트 (#136)

- src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
- src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
> Test: 장바구니 API 테스트 작성 (#148)

- src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
- src/main/java/com/jelly/zzirit/domain/order/repository/OrderRepository.java
- src/main/java/com/jelly/zzirit/domain/order/service/QueryOrderService.java
- src/main/java/com/jelly/zzirit/global/dto/PageResponse.java
> Closes #143 
- 기존의 주문 전체 조회 기능에 페이징 적용
> Feat: 주문 전체 조회 페이징 구현 (#143)

- build.gradle
> Closes #155
- Jacoco 테스트 제외 경로 설정
> Chore: Jacoco 테스트 제외 경로 설정 (#155)

- .gitignore
- build.gradle
- src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
- src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
- src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
- src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
- src/main/java/com/jelly/zzirit/domain/item/service/QueryItemService.java
- src/main/java/com/jelly/zzirit/global/config/QueryDslConfig.java
- src/main/java/com/jelly/zzirit/global/dto/PageResponse.java
- src/main/resources/application-dev.yml
- src/test/java/com/jelly/zzirit/domain/item/domain/fixture/ItemFixture.java
- src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
> Closes #151 
- querydsl 설정
- 상품 조회 동적 쿼리 적용
> Refactor: 상품 조회 리팩토링 (#151)

- src/test/java/com/jelly/zzirit/domain/item/contorller/TimeDealControllerTest.java
> Closes #130
- 테스트 간 데이터 중복으로 타임딜 등록 테스트 실패 문제 해결 (DB 초기화 추가)
- 테스트용 토큰 발행시 Redis를 이용하는 부분이 있어서 생긴 오류였습니다.
> Fix: 타임딜 등록 테스트 실패 문제 해결 (#130)

- src/main/java/com/jelly/zzirit/global/aspect/ConnectionProxyHandler.java
- src/main/java/com/jelly/zzirit/global/aspect/QueryCountAspect.java
- src/main/java/com/jelly/zzirit/global/aspect/QueryCounter.java
- src/main/java/com/jelly/zzirit/global/config/WebMvcConfig.java
- src/main/java/com/jelly/zzirit/global/interceptor/LoggingInterceptor.java
> Closes #164 
- N + 1 문제를 찾기 위한 쿼리 카운터를 추가했습니다.
> Feat: 쿼리 카운터 추가 (#164)

- src/main/java/com/jelly/zzirit/domain/admin/controller/AdminController.java
> Closes #169
현재 Swagger에 application/json으로 설정되어 있어 multipart/form-data로 수정
> Fix: 이미지 업로드 API Swagger 설정 (#169)

- src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
> Closes #171
- TimeDealItem 조회 후 getItem()으로 Lazy 로딩하던 방식 제거
- 머지 되고 직접 요청 해봐야 해결되었는지 확인 가능합니다.
> Fix: Lazy 객체 조회 제거 및 응답 생성 방식 개선

- build.gradle
- src/main/java/com/jelly/zzirit/global/config/securityconfig/SecurityConfig.java
- src/main/java/com/jelly/zzirit/global/security/filter/JwtFilter.java
- src/main/java/com/jelly/zzirit/global/wrapper/ResponseWrapper.java
- src/main/resources/application.yml
- src/test/java/com/jelly/zzirit/domain/cart/controller/CartControllerTest.java
- src/test/java/com/jelly/zzirit/domain/cart/controller/CartItemControllerTest.java
- src/test/java/com/jelly/zzirit/global/support/AcceptanceTest.java
- src/test/resources/application.yml
- src/test/resources/truncate.sql
> Closes #172 
- 모니터링 설정
- 테스트 독립
> Feat: 모니터링 설정 (#172)

- src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
- src/main/java/com/jelly/zzirit/domain/item/dto/request/ItemFilterRequest.java
- src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
- src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
- src/main/java/com/jelly/zzirit/domain/item/service/QueryItemService.java
- src/main/java/com/jelly/zzirit/global/util/StringUtils.java
- src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
> Closes #177 
- 상품 검색 Params Lsit -> String
- String Convert 추가
> Refactor: 상품 검색 Param 수정 (#177)

- src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
- src/main/java/com/jelly/zzirit/domain/order/dto/response/OrderFetchResponse.java
- src/main/java/com/jelly/zzirit/domain/order/entity/Order.java
- src/main/java/com/jelly/zzirit/domain/order/entity/OrderStatus.java
- src/main/java/com/jelly/zzirit/domain/order/mapper/OrderMapper.java
- src/main/java/com/jelly/zzirit/domain/order/repository/OrderRepository.java
- src/main/java/com/jelly/zzirit/domain/order/scheduler/OrderStatusScheduler.java
- src/main/java/com/jelly/zzirit/domain/order/service/OrderCancellationFacade.java
- src/main/java/com/jelly/zzirit/domain/order/service/order/CommandOrderService.java
- src/main/java/com/jelly/zzirit/domain/order/service/order/OrderCancelValidator.java
- src/main/java/com/jelly/zzirit/domain/order/service/order/OrderManager.java
- src/main/java/com/jelly/zzirit/domain/order/service/order/QueryOrderService.java
- src/main/java/com/jelly/zzirit/domain/order/service/pay/RefundService.java
- src/main/java/com/jelly/zzirit/domain/order/service/pay/TossPaymentValidation.java
- src/test/java/com/jelly/zzirit/domain/order/controller/order/OrderControllerTest.java
- src/test/java/com/jelly/zzirit/domain/order/domain/fixture/OrderFixture.java
- src/test/java/com/jelly/zzirit/domain/order/service/order/OrderManagerTest.java
- src/test/java/com/jelly/zzirit/domain/order/service/order/QueryOrderServiceTest.java
- src/test/java/com/jelly/zzirit/domain/order/service/order/TempOrderServiceTest.java
- src/test/java/com/jelly/zzirit/domain/order/service/pay/TossPaymentValidationTest.java
> Closes #158 
- 주문 취소 및 환불 로직 리팩토링
- 주문 상태를 변경하는 스케줄러 리팩토링
- 추후에 `벌크 연산` 등을 이용해 주문 목록의 상태를 변경해야 하지 않을까 싶습니다. 우선은 단순 구현한 상태입니다.
> Refactor: 주문 도메인 리팩토링 (#158)

- src/main/java/com/jelly/zzirit/domain/order/controller/OrderController.java
- src/main/java/com/jelly/zzirit/domain/order/repository/OrderRepository.java
- src/main/java/com/jelly/zzirit/domain/order/service/order/QueryOrderService.java
- src/test/java/com/jelly/zzirit/domain/order/controller/order/OrderControllerTest.java
> Closes #183 
- 정렬을 위한 쿼리 파라미터 `sort` 추가
- 디폴트는 최신순을 나타내는 `desc`, 역순은 `asc` 
> Feat: 주문 전체 조회 기능에 정렬 옵션 추가 (#183)

- src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
- src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
- src/main/java/com/jelly/zzirit/global/exception/custom/InvalidTimeDealException.java
> Closes #144
- 타임딜 생성 시 중복된 기간 등록 방지 기능 추가
- 타임딜 생성 시 시작/종료 시점에 따라 상태 자동 설정 기능 추가
> Feat: 타임 딜 생성 시 진행 기간 중복 제한 기능 구현 (#144)

- src/main/java/com/jelly/zzirit/domain/admin/controller/AdminController.java
- src/main/java/com/jelly/zzirit/domain/admin/dto/request/ItemUpdateRequest.java
- src/main/java/com/jelly/zzirit/domain/admin/service/CommandAdminService.java
- src/main/java/com/jelly/zzirit/domain/admin/service/CommandS3Service.java
- src/test/java/com/jelly/zzirit/domain/admin/controller/AdminControllerTest.java
- src/test/java/com/jelly/zzirit/domain/admin/service/CommandAdminServiceTest.java
> Closes #202 
- 상품 수정 API에 이미지 URL 수정 기능 추가
- FE 개발자님에 요청으로 추가했습니다
> Feat: 상품 수정 API에 이미지 URL 수정 기능 추가 (#202)

- src/test/java/com/jelly/zzirit/domain/item/contorller/ItemControllerTest.java
- src/test/java/com/jelly/zzirit/domain/item/domain/fixture/ItemFixture.java
- src/test/java/com/jelly/zzirit/domain/item/service/CommandTimeDealServiceTest.java
- src/test/java/com/jelly/zzirit/domain/item/service/QueryTimeDealServiceTest.java
- src/test/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerServiceTest.java
> Closes #188 
- 타임딜 등록, 조회에 대한 컨트롤러 테스트 제외한 컨트롤러, 서비스 테스트들을 포함하고 있습니다.
> Test: 타임딜 도메인 테스트 추가

- src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
- src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
- src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
- src/main/java/com/jelly/zzirit/domain/item/service/QueryItemService.java
- src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
> Refactor: 상품 조회 리팩토링 (#205)

- src/main/java/com/jelly/zzirit/domain/admin/controller/AdminController.java
- src/main/java/com/jelly/zzirit/domain/admin/dto/request/ItemCreateRequest.java
- src/main/java/com/jelly/zzirit/domain/admin/dto/request/ItemUpdateRequest.java
- src/main/java/com/jelly/zzirit/domain/admin/dto/response/AdminItemFetchResponse.java
- src/main/java/com/jelly/zzirit/domain/admin/service/CommandAdminService.java
- src/main/java/com/jelly/zzirit/domain/admin/service/CommandS3Service.java
- src/main/java/com/jelly/zzirit/domain/admin/service/QueryAdminService.java
- src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
- src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
- src/test/java/com/jelly/zzirit/domain/admin/controller/AdminControllerTest.java
- src/test/java/com/jelly/zzirit/domain/admin/service/QueryAdminServiceTest.java
- src/test/java/com/jelly/zzirit/global/support/AcceptanceTest.java
> Closes #200
- 목록 조회 시 정렬 추가 (테스트코드에 반영 완료)
- 테스트코드에 문서화 포함
- 그 외 자잘한 리팩토링
> Refactor: 관리자 상품 도메인 리팩토링 (#200)

- src/main/java/com/jelly/zzirit/domain/item/dto/request/TimeDealSearchCondition.java
- src/main/java/com/jelly/zzirit/domain/item/entity/Item.java
- src/main/java/com/jelly/zzirit/domain/item/entity/ItemStatus.java
- src/main/java/com/jelly/zzirit/domain/item/entity/stock/ItemStock.java
- src/main/java/com/jelly/zzirit/domain/item/infra/persist/TimeDealQueryRepositoryImpl.java
- src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
- src/main/java/com/jelly/zzirit/domain/item/repository/stock/ItemStockRepository.java
- src/main/java/com/jelly/zzirit/domain/item/scheduler/TimeDealStatusScheduler.java
- src/main/java/com/jelly/zzirit/domain/item/service/CommandItemService.java
- src/main/java/com/jelly/zzirit/domain/item/service/CommandTimeDealService.java
- src/main/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerService.java
- src/main/java/com/jelly/zzirit/global/dto/BaseResponseStatus.java
- src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
- src/test/java/com/jelly/zzirit/domain/item/service/QueryTimeDealServiceTest.java
- src/test/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerServiceTest.java
> Closes #208 
- 변경된 DB 반영하여 엔티티 수정
- 타임딜 조회, 검색 기능 수정
> Refactor: 타임딜 및 재고 관련 DB 수정사항 반영 (#208)

- .github/workflows/deploy-manual.yml
- src/main/java/com/jelly/zzirit/domain/item/entity/timedeal/TimeDeal.java
- src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
- src/main/java/com/jelly/zzirit/domain/item/service/TimeDealSchedulerService.java
- src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataGenerator.java
- src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataRunner.java
- src/test/java/com/jelly/zzirit/domain/admin/controller/AdminControllerTest.java
> Closes #216
- 타임딜 스케줄링 테스트 데이터 삽입
- 타임딜 복합 인덱스 적용(상태, 시작시간)
- 조회 시간 측정 로그 콘솔 출력
> Feat: 타임딜 테스트 데이터 2만 건 삽입, 타임딜 복합 인덱스 적용, 조회시간 측정 로그 찍기 (#216)

- src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
- src/main/java/com/jelly/zzirit/global/dataInit/DataInitializer.java
- src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataGenerator.java
- src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataRunner.java
- src/main/resources/data.sql
> Closes #257
- 상품 더미데이터 생성 조건 수정(상품 count 0일때 -> 2미만일때)
- 상품 더미데이터 삽입 시 FK 제약조건 반영하여 테이블 삭제 순서 변경
- mysql 일부 버전에서 limit 사용 안 되는 문제 -> repository 코드 변경
실행 전 DB 초기화를 추천 드립니다! 
```
DROP DATABASE IF EXISTS `zzirit-dev`;
CREATE DATABASE `zzirit-dev` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
```
실행 후 데이터가 잘 삽입되었는지 확인해봐주세요!
```
use `zzirit-dev`;
select count(*) from item; // 114
select count(*) from time_deal; // 20,000
```
> Fix: 상품 더미데이터 삽입 안 되는 이슈 해결 (#257)

- src/main/java/com/jelly/zzirit/domain/item/controller/ItemController.java
- src/main/java/com/jelly/zzirit/domain/item/dto/response/ItemFetchQueryResponse.java
- src/main/java/com/jelly/zzirit/domain/item/infra/persist/ItemQueryRepositoryImpl.java
- src/main/java/com/jelly/zzirit/domain/item/repository/ItemQueryRepository.java
- src/main/java/com/jelly/zzirit/domain/item/repository/TimeDealRepository.java
- src/main/java/com/jelly/zzirit/domain/item/service/QueryItemService.java
- src/main/java/com/jelly/zzirit/global/dto/PageResponse.java
- src/test/java/com/jelly/zzirit/domain/item/service/QueryItemServiceTest.java
> Fix: 상품 조회 필터링이 안되는 오류 (#251)

- src/main/java/com/jelly/zzirit/domain/order/service/message/OrderConfirmConsumer.java
- src/main/java/com/jelly/zzirit/global/dataInit/TimeDealDummyDataRunner.java
> fix: equal 조건 수정
